# docker-compose.yml
version: '3.8'

services:
  php:
    container_name: graphql-php-mysql
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  dbdata:
